<?php
/**
 * Seepossible
 * @package Seepossible_Newsletter
 * @copyright Copyright(C) 2015 Seepossible (contact@seepossible.com)
 * @author Seepossible <contact@seepossible.com>
 */

 /** @var \Magento\Framework\View\Element\Js\Components $block */
?>
<script type="text/x-magento-init">
    {
        "#newsletter-validate-detail": {
            "Seepossible_Newsletter/js/newsletter-subscription": {}
        }
    }
</script>
